### ISSUE TITLE
怎么训练自定义数据集

### ISSUE THREAD

**Issue by chenglong521** [ZhouYuxuanYX/BlockGCN#12]
可以训练自己的数据集吗？我看代码用的是3D骨骼，有提取方法吗？

**Comment by ZhouYuxuanYX** [comment]
请不要问和本文代码无关的问题，这个属于你自己需要学习的基础知识，谢谢

**Comment by ZhouYuxuanYX** [comment]
> 可以训练自己的数据集吗？我看代码用的是3D骨骼，有提取方法吗？

参见3d姿态估计相关论文。这个属于和本文不相关的基础问题，请不要提无关的问题，多花时间自行学习，谢谢。
