### ISSUE TITLE
论文问题

### ISSUE THREAD

**Issue by zhaokaipan** [ZhouYuxuanYX/BlockGCN#13]
请问您新写的《BlockGCN: Redefine Topology Awareness for Skeleton-Based Action Recognition》与之前您写的《Overcoming Topology Agnosticism: Enhancing Skeleton-Based Action Recognition through Redefined Skeletal Topology Awareness》对您的四模态识别结果展示的不一样，前者有较大的提升，但是您在github上并没有更新程序，请问您能提供更新之后的程序吗？

**Comment by ZhouYuxuanYX** [comment]
文章使用的方法已经更新了，这个代码也是最新的代码，请仔细阅读论文
