### ISSUE TITLE
About the meaning of three types Adjacency Matrix in ./graph/ntu_rgb_d.py

### ISSUE THREAD

**Issue by LlongXie** [ZhouYuxuanYX/BlockGCN#14]
Hi, dear Doctor, your work looks great and interesting.
Actually I don't know much about the field of action recognition, so I would like to ask some questions about the adjacency matrix.

In ./graph/ntu_rgb_d.py, from line 7 to 31
it is easy to understand that the first two graphs, maynum_node_1 = 11 and indices_1 = [0, 3, 5, 7, 9, 11, 13, 15, 17, 19, 20] refer to a rougher structure of the whole human body.

But what is the physical meaning of the third graph, that is, num_node_2 = 5 and indices_2 = [3, 5, 6, 8, 10]? 
Does it refer to the adjacency matrix relative to indices_1?

Thanks for your help, maybe you can point out which paper I should refer to. I am all gratitude.

**Comment by ZhouYuxuanYX** [comment]
Hi,

the file ntu_rgb_d.py is adopted from previous work, which is listed in the acknowledgment. Notably, we only use A for our code, thus the part of code you asked is irrelevant to our project.

Best,
Yuxuan
