### ISSUE TITLE
code problem

### ISSUE THREAD

**Issue by zhaokaipan** [ZhouYuxuanYX/BlockGCN#6]
why the code can not be runned    
and it lacks someting musted

**Comment by ZhouYuxuanYX** [comment]
If it's some environment issue, you should be able to handle it yourself. Otherwise your issue should be explicitly described here.

**Comment by zhaokaipan** [comment]
Thank you for answering my question. It is not a problem with the running environment. I have configured the environment and successfully ran train.sh. The training yaml file related to the UCLA data set is missing in your file. I downloaded this part from Found it in CTRGCN. When training the ucla data set, that is, when running the training script you gave, I encountered a tensor mismatch between network layers, specifically expressed as RuntimeError: The size of tensor a (8) must match the size of tensor b (16) at non-singleton dimension 0. This problem may be related to the BLOCKGCN model. Another problem is RuntimeError: Caught RuntimeError in replica 0 on device 0. When you were training, eight GPU cards were trained at the same time. ? I used two 3090 cards to train your model. In addition, I also want to know which version of torch you used during training, because I got RuntimeError: FIND was unable to find an engine when training ntu60. to execute this computation after trying 0 plans. This may be because my torch version number is too high. Thank you for taking the time to read my question and help me answer it. Thank you very much!

**Comment by zhaokaipan** [comment]
![ea478345331a12c665f76061de1e0b9](https://github.com/ZhouYuxuanYX/BlockGCN/assets/56015270/13d8ccb9-8986-4dee-bdf7-bd1ed25a8ad0)
This situation occurs when training data, do you know how to solve it?

**Comment by ZhouYuxuanYX** [comment]
This issue is not explicit enough to respond to.

**Comment by ZhouYuxuanYX** [comment]
Hi,

sorry for the late reply. The UCLA dataset only contains one person, while
NTU datasets assume a maximum number of two people. So NTU data has an
additional dimension with size 2, and our topological analysis has to be
adapted to such a dimension difference. In line 312-315,  the solution is
provided in the comments:
        # for ntu, two people at the same frame
        x = x.repeat(2,1)
        # for ucla, one person only
        #x = x

Could you please reopen an issue and ask this in Github, so that I can also
provide the answer there to avoid similar questions?

Best,
Yuxuan

**Comment by zhaokaipan** [comment]
感谢您的回复，我是在GitHub上给您提的问题，可能是自动发的邮件，这个关于ucla的部分我注意到了，所以我在这个问题下面删除了我之前的提问，十分感谢您的回复！

**Comment by ZhouYuxuanYX** [comment]
好的，麻烦您重新提交一下删除的问题呗，这样以后其他人要是也遇到同样问题就可以参考，谢谢

zhaokaipan ***@***.***>于2024年6月6日 周四上午8:53写道：

**Comment by zhaokaipan** [comment]
好的，我将重新提交一个新的问题，来描述之前的问题，十分感谢您的回复！
