### ISSUE TITLE
ucla训练问题

### ISSUE THREAD

**Issue by zhaokaipan** [ZhouYuxuanYX/BlockGCN#9]
我在按照您的readme复现实验的时候，训练ucla数据集时出现了神经网络层与层之间张量不匹配的现象，ucla训练yaml文件是从ctrgcn官方代码拷过来的，这部分您并没有提供，请问张量不匹配的现象该如何解决呢？

**Comment by ZhouYuxuanYX** [comment]
For the readers' information:

The UCLA dataset only contains one person, while NTU datasets assume a maximum number of two people. So NTU data has an additional dimension with size 2, and our topological analysis has to be adapted to such a dimension difference. In line 312-315,  the solution is provided in the comments:       
        # for ntu, two people at the same frame
        x = x.repeat(2,1)
        # for ucla, one person only
        #x = x
